all:
  hosts:
    node1:
      ip: 10.1.2.2
      access_ip: 10.1.2.2
      ansible_host: 10.1.2.2
    node2:
      ip: 10.1.2.3
      access_ip: 10.1.2.3
      ansible_host: 10.1.2.3
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        node1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
